//next
import Head from "next/head";
import Link from "next/link";
//react
import { useRef, useEffect } from "react";

export default function Home() {
  const landingLinkRef = useRef<HTMLAnchorElement>(null);

  useEffect(() => {
    if (landingLinkRef.current !== null) {
      landingLinkRef.current.click();
    }
  }, [landingLinkRef.current]);

  return (
    <>
      <Head>
        <title>Food One</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link ref={landingLinkRef} href="homepage">
        Hit
      </Link>
    </>
  );
}
